import type { Metadata } from 'next'
import { Montserrat } from 'next/font/google'
import './globals.scss'
import Header from './Components/Header/Header'
import Footer from './Components/Footer/Footer'
import Layout from './Components/Layout/Layout'

const fontStyle = Montserrat({ subsets: ['latin'], weight: ['400', '900'] })

export const metadata: Metadata = {
  title: 'Main Page',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className={fontStyle.className}>
        <Layout header={<Header />} main={children} footer={<Footer />} />
      </body>
    </html>
  )
}
