import { IService } from '@/shared/types/models'

export const serviceList: IService[] = [
  {
    card: {
      title: 'MVP от 2 месяцев',
      subtitle: 'Из ваших требований выделяем только самый основной функционал для оценки гипотез',
      description:
        'Такой подход помогает нашим клиентам на более ранней стадии посмотреть на свой продукт с разных сторон, получить обратную связь от своих потенциальных клиентов, оценить конкурентную среду и более точно сформировать функциональные требования для будущего развития продукта.',
      videoUrl: './videos/MVP.mp4',
    },
    isOrange: true,
  },
  {
    card: {
      title: 'МОБИЛЬНЫЕ ПРИЛОЖЕНИЯ',
      subtitle: '',
      description:
        'Учитывая ваши требования, разрабатываем нативные и кроссплатформенные приложения с уникальным дизайном и функционалом, полностью соответствующими вашим требованиям.',
      videoUrl: './videos/mobile.mp4',
      full_stack: [
        'React Native',
        'Fabric',
        'Tensorflow',
        'RabbitMQ',
        'Firebase',
        'Dio',
        'Sign in with Google',
        'Sign in with Facebook',
        'Flutter',
        'Dart',
        'Firebase Messaging',
        'Swift',
        'Java',
        'Kotlin',
        'CoreLocation',
        'MapKit',
        'CleanSwift(VIP)',
        'OneSignal',
        'AVFoundation',
        'Moya',
        'R.Swift',
        'Sass',
        'BLoC',
        'BLE',
        'Hive',
        'Dagger 2',
        'Kotlin Coroutines',
        'Kotlin Flow',
        'Retrofit',
        'MVI',
        'MVVM',
      ],
      url: 'mobile',
    },
  },
  {
    card: {
      title: 'ВЕБ ПРИЛОЖЕНИЯ И САЙТЫ',
      subtitle: '',
      description:
        'Реализуем широкий функционал для сайта вашей организации с комплексным решением. Опираясь на мировые тренды и собственный опыт, создаем удобные и функциональные интерфейсы.',
      videoUrl: './videos/web.mp4',
      full_stack: [
        'JavaScript',
        'Java',
        'Redux',
        'Axios',
        'Python',
        'Flask',
        'Celery',
        'Elasticsearch',
        'Pytorch',
        'Opencv',
        'Pycuda',
        'TensorRT',
        'Sqlalchemy',
        'Grpc',
        'Fastapi',
        'Zeromq',
        'Redis',
        'Docker',
        'Ffmpeg',
        'Webrtc (Janus)',
        'Websockets',
        'Firebase',
        'Django',
        'React Query',
        'React Router',
        'Styled Components',
        'PHP',
        'Mysql',
        'Laravel',
        'Voyager',
        'Redux Toolkit',
        'Konvs.js',
        'yarn',
        'Emotion',
        'Redux Form',
        'Kafka',
        'Keras',
        'GraphQL',
        'Next.js',
      ],
      url: 'web',
    },
  },
  {
    card: {
      title: 'ПРОГРАММНОЕ ОБЕСПЕЧЕНИЕ ДЛЯ ВСТРАИВАЕМЫХ СИСТЕМ',
      subtitle: '',
      description:
        'Разработка программного обеспечения для встраиваемых систем различного функционала, от реализации отдельных функций до полной автоматизации вашего бизнеса. Переход к реализации услуг в современном формате.',
      videoUrl: './videos/hardware.mp4',
      full_stack: ['C++'],
      url: 'hardware',
    },
  },
  {
    card: {
      title: 'OUTSTAFF',
      subtitle: '',
      description:
        'Мы предлагаем выделенную команду или отдельных специалистов по следующим направлениям:',
      videoUrl: './videos/outstaff.mp4',
      stack: ['Analytics', 'Design', 'Mobile', 'Web', 'Testing'],
    },
  },
]
